 create table items_tb (
       item_id int8 generated by default as identity,
        item_description varchar(255),
        item_type char(1),
        item_value float8,
        primary key (item_id)
    );

   create table orders_items_tb (
         order_item_id int8 generated by default as identity,
          quantity float8,
          total_value float8,
          item_id int8,
          order_id int8,
          primary key (order_item_id)
      );

     create table orders_tb (
         order_id int8 generated by default as identity,
          order_date timestamp,
          order_number int4,
          order_disccount float8,
          order_total_value float8,
          primary key (order_id)
      );

   